In [2]:
!pip install numpy 

In [3]:
import numpy as np

In [25]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [26]:
arr[1:4]

array([2, 3, 4])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [28]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[9,10,11,12]
arr=np.array([l1,l2,l3])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
arr.shape

(3, 4)

In [13]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [15]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
ls2=[6,7,8,9,10,11]
arr2=np.array(ls2)
arr2

array([ 6,  7,  8,  9, 10, 11])

In [18]:
arr2[4]

10

In [29]:
arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr[1:1,2:1]

array([], shape=(0, 0), dtype=int32)

In [30]:
arr[1:3,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [31]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [34]:
arr[0:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [36]:
arr[0:3,3:4]

array([[ 4],
       [ 8],
       [12]])

In [37]:
arr[:,:-1]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [38]:
arr[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [39]:
arr[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [43]:
arr2[3:]=100

In [44]:
arr2

array([  6,   7,   8, 100, 100, 100])

In [46]:
arr2[arr2<10]

array([6, 7, 8])

In [47]:
arr2*2

array([ 12,  14,  16, 200, 200, 200])

In [50]:
arr2*arr2

array([   36,    49,    64, 10000, 10000, 10000])

In [51]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [59]:
start=0
ip=int(input("Enter the size of array:"))
arr=np.arange(start,ip)
arr

Enter the size of array: 5


array([0, 1, 2, 3, 4])

In [58]:
start=0
ip=int(input("Enter the size of array:"))
arr=np.arange(ip,ip*10+1,ip)
arr

Enter the size of array: 5


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [60]:
ar1=np.arange(0,10).reshape(2,5)
ar2=np.arange(0,10).reshape(2,5)
ar1*ar2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [61]:
ar1+ar2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [62]:
ar1-ar2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [64]:
ar1/ar2

C:\Users\SIT\AppData\Local\Temp\ipykernel_14604\54374712.py:1: RuntimeWarning: invalid value encountered in divide
  ar1/ar2


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [68]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [67]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.random.rand(4,4)

array([[0.53638702, 0.5693185 , 0.15678887, 0.51039545],
       [0.93511338, 0.76395154, 0.47840771, 0.66235543],
       [0.7474066 , 0.17249954, 0.18640266, 0.14696508],
       [0.89367334, 0.65021356, 0.48408739, 0.96465653]])

In [75]:
np.random.randn(4,4)

array([[-1.5447995 ,  1.20788523, -0.28270778, -1.35960687],
       [ 1.54643572, -0.41893111,  0.24056733, -0.71189078],
       [-0.72031263, -0.92037139,  0.4722212 ,  2.25278991],
       [ 1.54577504,  0.09944193,  1.5647858 , -0.76258672]])

In [77]:
np.random.randint(0,100,8).reshape(4,2)

array([[42, 79],
       [86, 12],
       [89, 64],
       [57, 74]])